### ISSUE TITLE
Multiple device connection?

### ISSUE THREAD

**Issue by thealonealex** [ni554n/battarang-notifier-android#1]
Would it be difficult to have the battarang client be able to connect to multiple devices? So I can like, view my tablet's battery from both my phone and computer. It's not an issue, it's just a small convenience. If it's too hard to do it, I don't think it's something necessary

**Comment by ni554n** [comment]
Yes, because of the "no online account" architecture, it will increase complexity significantly. However Telegram integration can be a solution here. They have a web client that can also send notifications via browser (on both desktop and phone) if you don't want to install their app.

**Comment by thealonealex** [comment]
Interesting! Tho I found out that pc web browsers have to be open to send notifications, which kinda defeats the purpose? Unless there's an option for that

**Comment by ni554n** [comment]
Check out the **Frequently Asked Questions** section: https://battarang.anissan.com
