### ISSUE TITLE
indefinite loading "generating code"

### ISSUE THREAD

**Issue by pablo03v** [ni554n/battarang-notifier-android#2]
<img width="299" alt="Screenshot 2024-03-06 at 08 06 37" src="https://github.com/ni554n/battarang-notifier-android/assets/93644977/d3f4f6cd-024c-4bb6-b3e7-4b13f9303932">

**Comment by ni554n** [comment]
Thanks for letting me know about this issue. To help investigating further, could you please copy and paste the code that appears in your browser console when the issue occurs? To access the console, press `ctrl+shift+j` while the problem is happening.

**Comment by pablo03v** [comment]
the console is actually empty
<img width="1280" alt="Screenshot 2024-03-06 at 09 07 43" src="https://github.com/ni554n/battarang-notifier-android/assets/93644977/44ef0a7e-fbb2-47a8-b65f-a39557f59818">

**Comment by ni554n** [comment]
What browser (and version) is this? And have you enabled notification permission from **Site Settings** _(click the lock icon in the URL bar)_?

**Comment by pablo03v** [comment]
It's Chromium. Notifications are enabled for the site.

**Comment by ni554n** [comment]
Here it is working as expected on a fresh copy of Chromium.

I assume either your browser version is too old, or there's some configuration issue going on. Check if your browser notification is working from [this site](https://www.bennish.net/web-notifications.html).

![image](https://github.com/ni554n/battarang-notifier-android/assets/2310552/4af351ad-7dab-4984-8b8c-8b0bc5a19815)

**Comment by pablo03v** [comment]
> I assume either your browser version is too old

124.0.6352.0

> Check if your browser notification is working from [this site](https://www.bennish.net/web-notifications.html)

Notifications won't show up but request for permission is made and shown. Permissions are granted.

```
This is the output console.
Text will appear here when stuff happens.

Permission to display: granted
Notification #1 queued for display
Notification #1 showed
```

**Comment by ni554n** [comment]
Try these options:

https://frizbit.com/blog/troubleshooting-web-push-notifications-why-im-i-not-getting-notifications/

**Comment by pablo03v** [comment]
I just tried it on the site again, and the qrcode is being generated. I didn't change any configurations.

**Comment by ni554n** [comment]
What happens after you connect with the Battarang app? (You can send test messages by pressing the airplane button)
