### ISSUE TITLE
"Pause app activity if unused" keeps turning on automatically even if I already disabling it

### ISSUE THREAD

**Issue by renofummi46** [ni554n/battarang-notifier-android#4]
![Screenshot_2024-04-02-20-45-57-493_com miui securitycenter-edit](https://github.com/ni554n/battarang-notifier-android/assets/127815816/f9b0a08a-671b-42b5-bf6e-df8093e25a04)

**Comment by ni554n** [comment]
Xiaomi is notorious for doing stuff like this. Unfortunately, I don't have a device to test the app with.

It's possible their battery saver system resets it on low power mode. My suggestion is to turn the option off again and keep using it until you notice the app stop sending notifications. And if it does, then follow these instructions: https://dontkillmyapp.com/xiaomi

**Comment by BinoTheDino** [comment]
Had the same issue, instead of disabling the option in that page you have to go through app permissions first then disable it there
