### ISSUE TITLE
Receiver constantly disconnecting 

### ISSUE THREAD

**Issue by pato-gonzalez** [ni554n/battarang-notifier-android#6]
I own a Pixel 8 on Android 14.
I've followed the instructions in the app throughly many times and nevertheless the app keeps disconnecting on and on, rendering the app useless.
Is there anything I can do about it?

**Comment by ni554n** [comment]
Are you using browser or telegram as the receiver? How and when is it disconnecting? Are you getting any error message?

**Comment by pato-gonzalez** [comment]
I´m using browser, wantes to checkout using TG but haven´t found anything on FAQs.. Any clue on that?
It disconnects constantly, it just works a few times and all of a sudden i stops working with no error message at all, just a "Receiever got unpaired" notification

**Comment by ni554n** [comment]
What browser and OS (and version) are you using?

**Comment by pato-gonzalez** [comment]
I´m Using Arc Browser which is chromium based and MacOS Sonoma 14.5
On my Android device I´m using a Pixel 8 with android 14

**Comment by ni554n** [comment]
I assume it's an Arc browser issue. I haven't tested it there yet. I suggest you to enable the receiver on other browsers like Chrome or use the Telegram bot. Just start the [@battarang_bot](https://t.me/battarang_bot) and scan the QR code on your Pixel.

Please let me know the result.

**Comment by pato-gonzalez** [comment]
ive tried the telegram bot now and so far it seems to work. Thanks

**Comment by pato-gonzalez** [comment]
closing the issue for now
